---

services:
  _defaults:
    public: false
    autowire: false

  Knp\Rad\User\EventListener\Persistence\PasswordGenerationListener:
    arguments:
      - '@Knp\Rad\User\Password\Generator'
    tags:
      - name: doctrine.event_listener
        event: prePersist
        method: prePersist
        priority: 200

  Knp\Rad\User\Password\Generator\UniqidGenerator: ~

  Knp\Rad\User\Password\Generator:
    alias: Knp\Rad\User\Password\Generator\UniqidGenerator
